# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cinema.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import random

import varR
from result import *


class Final(QtWidgets.QMainWindow, Ui_Final):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class Result(QtWidgets.QMainWindow, Ui_RESULT):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class Ui_CINEMA(object):
    def __init__(self):
        self.finalWind = Final()
        self.resWind = Result()

    def setupUi(self, CINEMA):
        CINEMA.setObjectName("CINEMA")
        CINEMA.resize(820, 421)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CINEMA.sizePolicy().hasHeightForWidth())
        CINEMA.setSizePolicy(sizePolicy)
        CINEMA.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(CINEMA)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 10, 651, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setStyleSheet("color: rgb(172, 48, 176);")
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(490, 200, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 211, 34);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(142, 200, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 211, 34);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(490, 297, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 211, 34);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(142, 297, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 211, 34);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 821, 421))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("imgonline-com-ua-Resize-FcGngMeTKA.png"))
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.pushButton_3.raise_()
        self.pushButton.raise_()
        self.pushButton_4.raise_()
        self.pushButton_2.raise_()
        CINEMA.setCentralWidget(self.centralwidget)

        self.retranslateUi(CINEMA)
        QtCore.QMetaObject.connectSlotsByName(CINEMA)

    def retranslateUi(self, CINEMA):
        _translate = QtCore.QCoreApplication.translate
        CINEMA.setWindowTitle(_translate("CINEMA", "КИНО"))
        self.label.setText(_translate("CINEMA", "ЙУцйуйц"))
        self.pushButton_3.setText(_translate("CINEMA", "PushButton"))
        self.pushButton.setText(_translate("CINEMA", "PushButton"))
        self.pushButton_4.setText(_translate("CINEMA", "PushButton"))
        self.pushButton_2.setText(_translate("CINEMA", "PushButton"))

        self.btn_grp = QtWidgets.QButtonGroup()
        self.btn_grp.setExclusive(True)
        self.btn_grp.addButton(self.pushButton)
        self.btn_grp.addButton(self.pushButton_2)
        self.btn_grp.addButton(self.pushButton_3)
        self.btn_grp.addButton(self.pushButton_4)

        self.btn_grp.buttonClicked.connect(self.answer)

        self.list = [('В каком году сняли первый фильм?', '1895', '1897', '1901', '1900'),
                     ('Самый кассовый фильм?', 'Мстители: Финал', 'Аватар', 'Тачки 2',
                      'Титаник'),
                     ('Кто режиссёр фильма Кавзская Пленница?', 'Леонид Гайдай', "Владимир Этуш", "Юрий Никулин",
                      "Уильям Уайлер"),
                     ('Сколько сезонов в сериале "Игра Престолов"?', "8", "4", "7", "6"),
                     ('Человек с самым большим кол-вом Оскаров?', "Уолт Дисней", "Седрик Гиббонс", "Деннис Мьюрен",
                      "Альфред Ньюман"),
                     ('На какую оценку оцените себя?', '2', '3', '4', '5')]

        self.true = 0
        self.posl = [1, 2, 3, 4]
        random.shuffle(self.posl)
        self.label.setText(self.list[0][0])
        self.count = 1
        self.pushButton.setText(self.list[0][self.posl[0]])
        self.pushButton_2.setText(self.list[0][self.posl[1]])
        self.pushButton_3.setText(self.list[0][self.posl[2]])
        self.pushButton_4.setText(self.list[0][self.posl[3]])

    def answer(self, btn):
        if self.count < len(self.list):
            text = btn.text()
            if self.count == 1:
                answer = '1895'
                if text == answer:
                    self.true += 1
            if self.count == 2:
                answer = 'Мстители: Финал'
                if text == answer:
                    self.true += 1
            if self.count == 3:
                answer = 'Леонид Гайдай'
                if text == answer:
                    self.true += 1
            if self.count == 4:
                answer = '8'
                if text == answer:
                    self.true += 1
            if self.count == 5:
                answer = 'Уолт Дисней'
                if text == answer:
                    self.true += 1
            self.label.setText(self.list[self.count][0])
            random.shuffle(self.posl)
            self.pushButton.setText(self.list[self.count][self.posl[0]])
            self.pushButton_2.setText(self.list[self.count][self.posl[1]])
            self.pushButton_3.setText(self.list[self.count][self.posl[2]])
            self.pushButton_4.setText(self.list[self.count][self.posl[3]])
            self.count += 1
        elif self.count == 6:
            self.resWind.show()
            self.resWind.label_2.setText(f'{self.true}/5')
            if self.true == 0:
                self.resWind.label_3.setText('Вы совсем не молодец(')
            if self.true == 1:
                self.resWind.label_3.setText('Вы не молодец(')
            if self.true == 2:
                self.resWind.label_3.setText('Вам нужно больше стараться ^-^')
            if self.true == 3:
                self.resWind.label_3.setText('Неплохой результат!')
            if self.true == 4:
                self.resWind.label_3.setText('Вы молодец!')
            if self.true == 5:
                self.resWind.label_3.setText('Вы отлично справились!!!')
            self.hide()
            varR.schet += self.true
            if varR.predel == 7:
                self.finalWind.label_3.setText(f'{varR.schet}/25')
                self.resWind.hide()
                self.finalWind.show()
            print(varR.schet)