# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import varR


class Ui_Final(object):
    def setupUi(self, Final):
        Final.setObjectName("Final")
        Final.resize(595, 295)
        Final.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Final)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 601, 301))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("final.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 311, 81))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 90, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 250, 351, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(17)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 20, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        Final.setCentralWidget(self.centralwidget)

        self.retranslateUi(Final)
        QtCore.QMetaObject.connectSlotsByName(Final)

        self.btnGood = QtWidgets.QPushButton(self.centralwidget)
        self.btnGood.resize(121, 41)
        self.btnGood.move(470, 250)
        self.btnGood.setText('Я молодец ^_^')

        self.btnBad = QtWidgets.QPushButton(self.centralwidget)
        self.btnBad.resize(121, 41)
        self.btnBad.move(0, 250)
        self.btnBad.setText('Я не молодец T-T')

        self.btnGood.clicked.connect(self.end)
        self.btnBad.clicked.connect(self.end)

    def retranslateUi(self, Final):
        _translate = QtCore.QCoreApplication.translate
        Final.setWindowTitle(_translate("Final", "ОБЩИЙ РЕЗУЛЬТАТ"))
        self.label_2.setText(_translate("Final", "Ваш финальный результат:"))
        self.label_3.setText(_translate("Final", f"{varR.schet}/25"))
        self.label_4.setText(_translate("Final", "Можете оценить себя сами :)"))
        self.label_5.setText(_translate("Final", "Вы ответили на все вопросы!"))

    def end(self):
        self.btnGood.clicked.connect(QtCore.Application.instance().quit)



