# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'games.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random
import varR
from result import *


class Final(QtWidgets.QMainWindow, Ui_Final):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class Result(QtWidgets.QMainWindow, Ui_RESULT):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class Ui_GAMES(object):
    def __init__(self):
        self.pixmap = QtGui.QPixmap('321.jpg')
        self.resWind = Result()
        self.finalWind = Final()

    def setupUi(self, GAMES):
        GAMES.setObjectName("GAMES")
        GAMES.resize(820, 425)
        self.centralwidget = QtWidgets.QWidget(GAMES)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 820, 444))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imgonline-com-ua-Resize-7PIYQzIW53FC6sJ.png"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(142, 230, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(197, 36, 15);")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(55, 40, 751, 150))
        font = QtGui.QFont('MS Serif')
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_2.setStyleSheet("color: rgb(0, 255, 255);")
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(142, 327, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(197, 36, 15);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(490, 230, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(197, 36, 15);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(490, 327, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(197, 36, 15);")
        self.pushButton_4.setObjectName("pushButton_4")
        GAMES.setCentralWidget(self.centralwidget)

        self.retranslateUi(GAMES)
        QtCore.QMetaObject.connectSlotsByName(GAMES)

    def retranslateUi(self, GAMES):
        _translate = QtCore.QCoreApplication.translate
        GAMES.setWindowTitle(_translate("GAMES", "ИГРЫ"))
        self.pushButton.setText(_translate("GAMES", "PushButton"))
        self.label_2.setText(_translate("GAMES", "ЙУцйуйц"))
        self.pushButton_2.setText(_translate("GAMES", "PushButton"))
        self.pushButton_3.setText(_translate("GAMES", "PushButton"))
        self.pushButton_4.setText(_translate("GAMES", "PushButton"))

        self.btn_grp = QtWidgets.QButtonGroup()
        self.btn_grp.setExclusive(True)
        self.btn_grp.addButton(self.pushButton)
        self.btn_grp.addButton(self.pushButton_2)
        self.btn_grp.addButton(self.pushButton_3)
        self.btn_grp.addButton(self.pushButton_4)

        self.btn_grp.buttonClicked.connect(self.answer)

        self.list = [('В каком году проводился первый The International?', '2011', '2009', '2014', '2010'),
                     ('Кто самый богатый киберспортсмен?', 'n0tail', 'JerAx', 'S1mple', 'Miracle-'),
                     ('Как называется 1 способность героя Pudge из Dota 2?', 'Meet Hook', "Mask of Madness", "Rot",
                      "Chop Chop"),
                     ('Сколько в основной серии Counter-Strike вышло версий?', "3", "4", "5", "6"),
                     ('Какая организация заработала больше всего денег?', "Team SoloMid", "Cloud9", "Team Liquid",
                      "FaZe Clan"),
                     ('На какую оценку оцените себя?', '2', '3', '4', '5')]

        self.true = 0
        self.posl = [1, 2, 3, 4]
        random.shuffle(self.posl)
        self.label_2.setText(self.list[0][0])
        self.count = 1
        self.pushButton.setText(self.list[0][self.posl[0]])
        self.pushButton_2.setText(self.list[0][self.posl[1]])
        self.pushButton_3.setText(self.list[0][self.posl[2]])
        self.pushButton_4.setText(self.list[0][self.posl[3]])

    def answer(self, btn):
        if self.count < len(self.list):
            text = btn.text()
            self.label_2.setText(self.list[self.count][0])
            random.shuffle(self.posl)
            self.pushButton.setText(self.list[self.count][self.posl[0]])
            self.pushButton_2.setText(self.list[self.count][self.posl[1]])
            self.pushButton_3.setText(self.list[self.count][self.posl[2]])
            self.pushButton_4.setText(self.list[self.count][self.posl[3]])
            if self.count == 1:
                answer = '2011'
                if text == answer:
                    self.true += 1
            if self.count == 2:
                answer = 'n0tail'
                if text == answer:
                    self.true += 1
            if self.count == 3:
                answer = 'Meet Hook'
                if text == answer:
                    self.true += 1
            if self.count == 4:
                answer = '5'
                if text == answer:
                    self.true += 1
            if self.count == 5:
                answer = 'Team SoloMid'
                if text == answer:
                    self.true += 1
            self.count += 1
        elif self.count == 6:
            self.resWind.show()
            self.resWind.label_2.setText(f'{self.true}/5')
            if self.true == 0:
                self.resWind.label_3.setText('Вы совсем не молодец(')
            if self.true == 1:
                self.resWind.label_3.setText('Вы не молодец(')
            if self.true == 2:
                self.resWind.label_3.setText('Вам нужно больше стараться ^-^')
            if self.true == 3:
                self.resWind.label_3.setText('Неплохой результат!')
            if self.true == 4:
                self.resWind.label_3.setText('Вы молодец!')
            if self.true == 5:
                self.resWind.label_3.setText('Вы отлично справились!!!')
            self.hide()
            varR.schet += self.true
            if varR.predel == 7:
                self.finalWind.label_3.setText(f'{varR.schet}/25')
                self.resWind.hide()
                self.finalWind.show()
            print(varR.schet)