# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'varR.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from sport import *
from history import *
from science import *
from all import *
from games import *
from cinema import *
from geogr import *
from final import *
from sps import *

schet = 0
predel = 0


class sps(QtWidgets.QMainWindow, Ui_end):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class Final(QtWidgets.QMainWindow, Ui_Final):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class Geogr(QtWidgets.QMainWindow, Ui_GEOGR):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class Cinema(QtWidgets.QMainWindow, Ui_CINEMA):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class Games(QtWidgets.QMainWindow, Ui_GAMES):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class All(QtWidgets.QMainWindow, Ui_ALL):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class Science(QtWidgets.QMainWindow, Ui_SCIENCE):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class History(QtWidgets.QMainWindow, Ui_HISTORY):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class Sport(QtWidgets.QMainWindow, Ui_SPORT):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class Ui_Choose(object):
    def __init__(self):
        self.endWind = sps()
        self.predel = 0
        self.allWind = All()
        self.scienceWind = Science()
        self.historyWind = History()
        self.sportWind = Sport()
        self.gamesWind = Games()
        self.cinemaWind = Cinema()
        self.geogrWind = Geogr()
        self.finalWind = Final()

    def setupUi(self, Choose):
        Choose.setObjectName("Choose")
        Choose.resize(691, 406)
        Choose.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Choose)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(138, 36, 411, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(43)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 43pt \"Segoe Print\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 150, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(76, 76, 76);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(71, 150, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(44, 167, 0);\n"
"background-color: rgb(255, 255, 69);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(71, 236, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(203, 142, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(71, 322, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(255, 142, 12);\n"
"background-color: rgb(144, 0, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(498, 150, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(88, 112, 143);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(498, 236, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("color: rgb(170, 85, 0);\n"
"background-color: rgb(101, 103, 73);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(500, 320, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("color: rgb(38, 0, 255);\n"
"background-color: rgb(8, 8, 3);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -20, 691, 451))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("imgonline-com-ua-Resize-6aB6VuAxuee3f5x.png"))
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_5.raise_()
        self.pushButton_4.raise_()
        self.label.raise_()
        self.pushButton_2.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton.raise_()
        Choose.setCentralWidget(self.centralwidget)

        self.retranslateUi(Choose)
        QtCore.QMetaObject.connectSlotsByName(Choose)

    def retranslateUi(self, Choose):
        _translate = QtCore.QCoreApplication.translate
        Choose.setWindowTitle(_translate("Choose", "РАЗДЕЛЫ"))
        self.label.setText(_translate("Choose", "Разделы"))
        self.pushButton.setText(_translate("Choose", "Общие"))
        self.pushButton_2.setText(_translate("Choose", "Спорт"))
        self.pushButton_3.setText(_translate("Choose", "Наука"))
        self.pushButton_4.setText(_translate("Choose", "Кино"))
        self.pushButton_5.setText(_translate("Choose", "Игры"))
        self.pushButton_6.setText(_translate("Choose", "История"))
        self.pushButton_7.setText(_translate("Choose", "География"))

        self.pushButton_2.clicked.connect(self.sport)
        self.pushButton_6.clicked.connect(self.history)
        self.pushButton_3.clicked.connect(self.science)
        self.pushButton.clicked.connect(self.all)
        self.pushButton_5.clicked.connect(self.games)
        self.pushButton_4.clicked.connect(self.cinema)
        self.pushButton_7.clicked.connect(self.geogr)

    def sport(self):
        self.sportWind.show()
        self.pushButton_2.clicked.disconnect(self.sport)
        self.pushButton_2.clicked.connect(self.end)
        varR.predel += 1

    def history(self):
        self.historyWind.show()
        self.pushButton_6.clicked.disconnect(self.history)
        self.pushButton_6.clicked.connect(self.end)
        varR.predel += 1

    def science(self):
        self.scienceWind.show()
        self.pushButton_3.clicked.disconnect(self.science)
        self.pushButton_3.clicked.connect(self.end)
        varR.predel += 1

    def all(self):
        self.allWind.show()
        self.pushButton.clicked.disconnect(self.all)
        self.pushButton.clicked.connect(self.end)
        varR.predel += 1

    def games(self):
        self.gamesWind.show()
        self.pushButton_5.clicked.disconnect(self.games)
        self.pushButton_5.clicked.connect(self.end)
        varR.predel += 1

    def cinema(self):
        self.cinemaWind.show()
        self.pushButton_4.clicked.disconnect(self.cinema)
        self.pushButton_4.clicked.connect(self.end)
        varR.predel += 1

    def geogr(self):
        self.geogrWind.show()
        self.pushButton_7.clicked.disconnect(self.geogr)
        self.pushButton_7.clicked.connect(self.end)
        varR.predel += 1

    def end(self):
        self.endWind.show()